---
- name: Remove DVD repository from sources.list
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^deb cdrom:'
    state: absent
  become: yes

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - debconf-utils
    - sudo
    - python3-pip
    - git
    - unzip
    - ncdu
    - tree
    - vim 
    - mc
    - ccze
    - shutter
    - remmina*
    - ttf-mscorefonts-installer
...
