---
- name: Configure servers
  hosts: ----
  become: true
  vars_files:
    - ./vars/vault.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_python_driver: PyMySQL
  roles:
    #- common
    #- sudo
    #- apache2
    #- php  
    #- mysql
    #- phpmyadmin
    - add_glpi_site
...
