---
- name: Install WordPress
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"

- name: Extract WordPress
  ansible.builtin.unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "/var/www/html/"
    remote_src: yes

- name: Copy WordPress configuration
  template:
    src: wordpress/wp-config.php.j2
    dest: "/var/www/html/wp-config.php"

- name: Set correct permissions
  file:
    path: "/var/www/html/{{ item }}"
    state: directory
    recurse: yes
    mode: "0755"
  loop:
    - wp-content
    - wp-content/plugins
    - wp-content/themes

