---
- name: Configure servers
  hosts: 127.0.0.1
  become: true
  vars_files:
    - ./vars/vault.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_python_driver: PyMySQL
  roles:
    - common
    - sudo
...
